name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Release Package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: yarn install --imutable

      - name: Configure git user
        run: |
          git config --global user.name "rahmatsaputra"
          git config --global user.email "rahmatsaputra@users.noreply.github.com"

      - name: Build package
        run: yarn build || yarn prepare || true # atau yarn prepare

      - name: Release with release-it
        run: npx release-it --ci
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
